/*
 * This source file was generated by the Gradle 'init' task
 */
package com.simdikta;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class AppTest {
    @Test void contextLoads() {
        // This test will pass if the Spring context loads successfully
        assertTrue(true, "Spring context should load");
    }
}
